### PR TITLE
Ui/main menu

### PR DESCRIPTION
**Pull request by corentinartaud**
## What issue is this PR solving?
Closes: #16, #17 

## Description of change
This PR adds a Main Menu with the following sections:
- Title
- Play
- Options
   - Volume
   - Back
- Quit

## How to reproduce the changes
1. Select scene `MainMenu`
2. File -> Build Settings
3. Build and Run
4. Select `1400 x 900`

## Screenshots or GIFs
539efd5714ef8a879d56e2f79536ac53

### CODE REVIEW

**Comment by corentinartaud** [comment]
@mjimenez98 Just fixed the merge conflicts. You should be able to merge into develop without any problems when you get to it.

**Comment by mjimenez98** [comment]
@corentinartaud It looks great! And nice easter egg message in debug when quitting the game😉

One minor question, if I select anything lower than `1400 x 900` I don't get the full menu. The same happens in the Unity editor. Is this something we should correct before merging?

**Comment by corentinartaud** [comment]
@mjimenez98 Had to find something creative ;) 

Yes that is absolutely something that needs to be corrected and absolutely my fault! I'll get it on it and push a fix to UI/MainMenu by the end of tonight latest tomorrow. (Completely forgot about rescaling the screen size...my bad)

**Comment by mjimenez98** [comment]
@corentinartaud Perfecto! No worries🙌

**Comment by corentinartaud** [comment]
@mjimenez98 I just fixed the resolution issue! My apologies for the delay! Please review and should be good to merge into master!

**Pull request merged**
