### PR TITLE
Hud+screens

### PR DESCRIPTION
**Pull request by corentinartaud**
## What issue is this PR solving?
Closes: https://github.com/Luna-Interactive/catastrophe/issues/27

## Description of change
* Added over head health bar for player
* Added MiniMap for HUD (WIP - much more to come)
* Added slot position (need to find our power-ups tho)

## Screenshots or GIFs
Screen Shot 2019-10-30 at 00 33 22

Screen Shot 2019-10-30 at 00 33 36

### CODE REVIEW

**Comment by corentinartaud** [comment]
@mjimenez98 I added a game over sequence if you want to show it off for demo tomorrow. The win and lose screens are a little more complicated as I will have to see with backend since it will be event driven. (you should test it out for yourself as its animated)

Screen Shot 2019-10-31 at 00 06 32

**Comment by gnoriega27** [comment]
@yshrdbrn here

**Comment by corentinartaud** [comment]
@gnoriega27 Absolutely! Very good idea.

**Comment by mjimenez98** [comment]
@gnoriega27 I will create a new issue for it. Thank you!

@corentinartaud That is beautiful. Would the game over screen show up for all players?

**Comment by corentinartaud** [comment]
@mjimenez98 sadly not ... https://github.com/Luna-Interactive/catastrophe/pull/56#issuecomment-548208886

**Comment by mjimenez98** [comment]
@corentinartaud is working on a new branch that will include these change. A new PR will be opened for it.

**Pull request closed without merging**
