### PR TITLE
Backend/team assignment

### PR DESCRIPTION
**Pull request by gnoriega27**
## What issue is this PR solving?
Closes: #67 

## Description of change
All players in the game now belong to a team, with their correct colour identifier.

## How to reproduce the changes
Run +7 instances of the game.

## Screenshots or GIFs
Sorry for the bad quality.
photo_2019-11-09_16-10-31

Up to 12 players can play now.

### CODE REVIEW

**Comment by gnoriega27** [comment]
@mjimenez98  Weird. I got up to 12 players and no problem. Let me check.

**Comment by mjimenez98** [comment]
I just ran it again and it works, sorry about that, do not know what happened before. Sadly, I had another problem: the game accepted 10 players. 

Screen Shot 2019-11-09 at 5 53 56 PM

Can we lock it down to 9 here? Or is this a status we can add later on when we have a lobby? For instance, if lobby moves on to game, then server is no longer joinable.

**Comment by gnoriega27** [comment]
Yeah was about to upload a picture showing that it works. 
Regarding the lobby part and team locking mechanism, that is a matter for another issue (#88) and (#26).

**Comment by mjimenez98** [comment]
@gnoriega27 That is fair, I will add it to #88 instead of to #26 since it is the one related to backend.

Good stuff🏅 Thank you for taking care of this one!

**Comment by gnoriega27** [comment]
Should we merge?

**Comment by mjimenez98** [comment]
@gnoriega27 Yes!

**Pull request merged**
