### PR TITLE
Bullet collision detection & damage recognition

### PR DESCRIPTION
**Pull request by yshrdbrn**
## What issue is this PR solving?
Closes: #121 
Closes: #128 
Closes: #129 
Closes: #130 

## Description of change
This PR resolves the issues with the bullet implementation (except for the bullet width).
Changes in the PR:
* Bullets now get destroyed at a specific range. Each gun's bullet has a different range. We may have to balance each gun's range in the playtest.
* Hit detection is now done through bullet collision instead of raycasting.

### CODE REVIEW

**Comment by gnoriega27** [comment]
@mjimenez98 Regarding 1 and 2. I don't think the damaged/range should be tin this PR, that should be done in another PR. This is just to demostrate the new bullet collision mechanism.

**Comment by yshrdbrn** [comment]
@mjimenez98 Goddamn look at those gifs lol. #dedication haha. Yeah I see the shotgun is too OP now. Actually, I made it like this to test. We should address the range and damage of each gun tomorrow. 

About the 3, unfortunately I can't think of any solutions for it now. I guess a way to make this more intuitive is to add sounds to bullets. When they hit the car you hear a sound so you know you hit something.

**Comment by mjimenez98** [comment]
@gnoriega27 That is a fair remark. I included it because he addressed it in the _closes_ statements up top.

@yshrdbrn I checked and before the bullets used to go through object so 3. wasn't happening. For 2., are the bullet trails the same for the player shooting and the replicas in other players' views?

**Comment by yshrdbrn** [comment]
@mjimenez98 Fair enough. Maybe I shouldn't have merged the PR. I'll create a general issue for gun range/damage balancing so we don't forget. About the bullet not appearing, I'm not sure why the bullets went through before and don't go through now. I didn't change where bullets were instantiated and didn't add any extra collision detection conditions 🤔
For your last question, yes the bullets are the same. The only difference is the bullets inited from other people don't send out damage events when hitting the player.

**Comment by mjimenez98** [comment]
Interesting! Very cool to know. Thank you for the conversation :D

**Pull request merged**
