### PR TITLE
Master

### PR DESCRIPTION
**Pull request by corentinartaud**
Merging master into develop.

### CODE REVIEW

**Comment by yshrdbrn** [comment]
@corentinartaud Looks good.  @mjimenez98 thanks for updating .gitignore and .gitattributes!
The only thing is that the commit https://github.com/Luna-Interactive/catastrophe/pull/92/commits/5f6ca89341cf97bc38c61bb1e9c6897968959f70 changes the Bolt build mode to "release" (which was meant to live on master only). I'd prefer if you could push another commit here to change the build mode back to "debug"

**Comment by mjimenez98** [comment]
@yshrdbrn Could we change the build mode directly in develop? That way we would keep master on release, and develop on debug.

**Comment by gnoriega27** [comment]
Any update on this?

**Comment by mjimenez98** [comment]
@gnoriega27 Would you be able to commit to develop the change to debug mode ? It would be right after this so everybody can work with develop on debug mode.

**Comment by gnoriega27** [comment]
You want me to create a new PR for that? or should I push directly to develop?

**Comment by mjimenez98** [comment]
@gnoriega27 You can push directly to develop. Going forward with this one so nothing blocks you.

**Pull request merged**
