### PR TITLE
Fix for the flag and ammo count

### PR DESCRIPTION
**Pull request by yshrdbrn**
## What issue is this PR solving?
Closes: #124 
Closes: #155 
Closes: #165 

## Description of change
This PR fixes two issues that we saw during the playtest on Saturday:
 * Ammo count UI not showing player's ammo count all the time
 * Inconsistency across clients when a player took the flag

### Bonus
The PR also introduces a hacky solution to multiple people taking the flag at the same time. At the end of everyone's flag-taking animation, only one player should have the flag now. 

## How to test
Please go over the stuff mentioned above and see if they're actually fixed! thanks 😃

### CODE REVIEW

**Comment by lyonelz96** [comment]
Flag works beautifully.

Only thing I noticed, is that the ammo issue is still there. Say for example I have 5/30 on the AR, and I get killed. When I respawn I still see 5/30, when I shoot it goes back to its normal count.

**Comment by yshrdbrn** [comment]
@lyonelz96 aaah good catch, I forgot to fix that. I pushed a fix for it. Would you check again? Thanks dude.

**Comment by lyonelz96** [comment]
@yshrdbrn  
It works for the gun that you die with, but not for the "inactive" ones.
For example, if I have the AR at 0/30, and shotgun at 0/8, and i'm wielding the shotgun when I die, on respawn the shotgun will be at 8/8 but the AR will still be at 0/30.

**Comment by yshrdbrn** [comment]
@lyonelz96  FUUUCKKK I'M TERRIBLE AT THIS. I'll have a fix for that coming right up 😂

**Comment by yshrdbrn** [comment]
@lyonelz96 NOW it should be fixed (I really hope you don't find another bug 😂)

**Comment by lyonelz96** [comment]
@yshrdbrn  LOL

Everything looks delicious now!

**Pull request merged**
