### PR TITLE
Corentin/menu error fix

### PR DESCRIPTION
**Pull request by corentinartaud**
## What issue is this PR solving?
Closes: https://github.com/Luna-Interactive/catastrophe/issues/176
Closes: https://github.com/Luna-Interactive/catastrophe/issues/164
Closes: https://github.com/Luna-Interactive/catastrophe/issues/74 
Closes: https://github.com/Luna-Interactive/catastrophe/issues/72

## Description of change
This fixes the issue with the NOT READY/READY states being not properly reset when going back to main menu front page. It also fixes the issue for the spectator joining the game and having wrong team placements. 
The spectator can:
- Join and Host the Game
- Join as Client while in lobby
- Jon as Client while in game

This PR also adds the necessary mass on the player rigid body which address #72 

## How to reproduce the changes
Play the game

## Screenshots or GIFs
Too lazy...

### CODE REVIEW

**Comment by lyonelz96** [comment]
@corentinartaud  Cool so I found a few things.

1.  READY/NOT READY still faulty
  - To replicate:
    - Run two instances of the game
    - Host whichever mode on whichever instance
    - Join the game with the other instance
    - Click the not ready button (Now you should have Ready)
    - Force start the game 
    - Win/Lose a game
    - Without closing any instance, host again 
    - The button should be on Ready, and i'm not able to change it.

2.  If the spectator hosts a game, and the game finishes. The spectator gets stuck in an empty game,
it can't go back to the lobby or do anything.

3.  Spectator joins the game, and they count as players.
On the picture below, the only window that is a player is the one on the top left and says "Player" haha, all the other ones are spectators. Even then when I pressed ready on all of them, the game went ahead and started.
Yeh

**Comment by corentinartaud** [comment]
@lyonelz96 Please test with the new fixes I added and let me know if you still have issues.

**Comment by lyonelz96** [comment]
@corentinartaud 
I ran into an issue connecting to a game.

Window on the right I joined as a player, left is host
image

This is what it looks like when I force start the game
image

  - The spectator from what I saw is working perfectly now! I just have some minor nitpicking. I think the Return To Lobby logo should be smaller and in the corner OR If it's not too hard to implement, maybe even make it so that a whole screen comes up with just "Return To Lobby" option, since when you are on the free roam camera you can't really click on it. Minor details, not essential to implement if it's too time consuming.

**Comment by mjimenez98** [comment]
@corentinartaud Can this PR please be squashed when merged?

**Pull request merged**
