### PR TITLE
Develop ui

### PR DESCRIPTION
**Pull request by corentinartaud**
## What issue is this PR solving?
Closes: None

## Description of change
Added HUD which includes:
- MiniMap (which has been modified still needs work tho)
- Timer
- Slots for Power up
Added Health bar on top of player prefab with player health script

## How to reproduce the changes
Play the game

## Screenshots or GIFs
Screen Shot 2019-11-05 at 21 59 45

### CODE REVIEW

**Comment by stevau5** [comment]
@corentinartaud After reviewing the PR, I noticed a couple bugs. 
1. The Time isn't synchronized across builds. The timer only starts for the players once they join server, the time isn't global, it's per instance. 
2. Starting a server actually adds a player now for some reason. The spectator system is no longer accessible.
3. The HUD needs to be scaled with screen size. 

Check the attached image concerning the 3 issues. 

Annotation 2019-11-05 223817

**Comment by gnoriega27** [comment]
Agreed with Steven, there is some bug fixes to be done, but overall it works fine,
I got a couple of ideas to fix the "global time". Will discuss in depth with @corentinartaud

**Comment by mjimenez98** [comment]
@stevau5 I would vouch for reverting this until the bugs are squashed. Would you be okay with this?

**Comment by corentinartaud** [comment]
@mjimenez98 The bugs are not actually bugs. The only bug that needed fixing was the scaling which has been done. For the global time and player spawning, it is normal. This is actually how the game should be right now since there is not spectator option within the menu. This will be added with the new menu system and for global time I just have to talk to back end about the event otherwise the skeleton is there.

**Comment by mjimenez98** [comment]
@corentinartaud The last changes we made before the demo, however, were directly pushed to master. Master is ahead of develop.

We could merge the changes made here to develop, but not before updating develop to match master. What do you think?

**Comment by corentinartaud** [comment]
@mjimenez98 Yup sounds good. Revert and i'll make the changes accordingly. Let me know when its done.

**Comment by mjimenez98** [comment]
@corentinartaud Good to merge with develop! Thank you for waiting and sorry about that.

**Pull request merged**
