### PR TITLE
Multiplayer Shooting + Simple respawn mechanism

### PR DESCRIPTION
**Pull request by yshrdbrn**
## What issue is this PR solving?
Closes: #12 

## Description of change
This PR adds the ability to shoot other players. Their health gets decreased as soon as they are hit and everything gets synced across clients.
It also implements a simple respawn mechanism. You respawn at your base as soon as you die.

List of all changes:
* Created a Bolt event called PlayerDamageEvent
* Implemented the utility function `SendPlayerDamageEvent()` and the callback function `OnEvent(PlayerDamageEvent)` for it.
* Sent a PlayerDamageEvent if a player hits another player from another team (changes in *PlayerAttack.cs*)
* Synchronized player health across the network (changes in *PlayerController.cs* and *PlayerHealth.cs*)
* Implemented respawn mechanism (`Death()` defined in *PlayerHealth.cs*)

## How to reproduce the changes
Run two instances of the game and try to shoot with one player to another. You should see the other player's health decreasing. If a player's health reaches 0, he will respawn at his base instantly.

## Screenshots or GIFs
Sorry I didn't take any screenshots!

### CODE REVIEW

**Comment by mjimenez98** [comment]
This is a beauty, really really cool 🏆 

A few notes:
1. Player receiving shots does not see the bullets.
2. This is not about your branch but more of a note for design. It's hard to see if you are hitting the other player or not. Once we have all the FX it could be more clear, but in addition to that it wouldn't hurt to have a bigger health bar.

Please let me know your thoughts, and great work as always!

**Comment by yshrdbrn** [comment]
@mjimenez98 thanks for the feedback! I agree with both. I'll fix the first issue in this PR. We can have a separate issue for the second one.

**Comment by yshrdbrn** [comment]
@mjimenez98 Addressed the bullet trail issue. Please check, thanks!

**Comment by mjimenez98** [comment]
I can now see the trail but the sound was not replicated -- from what I could tell. Also, bullets are not destroyed on collision with an enemy😞

**Comment by mjimenez98** [comment]
I acknowledge you noticed this yesterday at the meeting, but just so it is here in writing:

1. Sometimes I shoot and I don't see the bullet, but another player does.
2. Sometimes I shoot and nobody sees the bullet although I still hear the sound.
3. Sometimes I shoot and I see the bullet, but another player does not.

Are these issues you would like to tackle before merging, or should I create a separate bug issue for them?

**Comment by yshrdbrn** [comment]
@mjimenez98 I provided basic fixes for bullet-related issues (sound, trails, shooting intervals). I think it's better to do any further fixes in another PR. I am not super confident about my code after the rebase (it was a big one!). I checked the features added in the PR to see if they still work, everything seems to work. Please briefly check to see if everything is ok!

Another note:
I used Lyonel's sound fx APIs to generate sound but from what I saw it doesn't properly take the sound source's position into account (for example walking sound is as loud when an enemy walks compared to own player's walk).

**Comment by lyonelz96** [comment]
Awesome!, besides the obvious sound issues. Looks good, I did encounter 2 things in my quick test.

1. Bullets dissapearing as if i'm hitting the player (But i'm not)
What

2. Bullets going through the player but still damaging them.
What2

**Comment by yshrdbrn** [comment]
@lyonelz96 Thanks for checking dude! (cool gifs goddamn). Yes, I'm aware of that but I forgot to mention. This is because the damage verification is done using raycast but the bullet destruction is done using collisions. So, the reason you see this happening is that sometimes the bullet object hits but the raycast doesn't detect the hit or vice versa.
We should definitely fix that. I suggest creating another issue for this and use bullet collisions instead of raycasting to make it consistent.

**Comment by lyonelz96** [comment]
@yshrdbrn  Ahh I see. Sounds good we can fix that issue in another PR.

Just a few clarifications and we should be good to go.

1. For the sound issues, you want to fix that in another PR as well? I'm not sure what's happening either but we can discuss that and fix it separately.

2. For the respawn, the player atm is respawning immediately, I think that was the intention of this PR? and we're going to change that for the final thing? Just making sure.

3. I forgot to test the different weapons, but for now we haven't implemented different damage or anything like that right? For example the sniper doing more damage than the AR. If we did I can go back and check that's working properly.

**Comment by yshrdbrn** [comment]
@lyonelz96 answering your comments:
* Yeah we should discuss sound issues and fix that. I think that is outside the scope of this PR.
* Good point. The respawn mechanism in this PR has some problems and needs to be fixed (for example we need to implement timeout when you die and to properly respawn the player). Since we already have an issue for this, I won't close that issue when this PR goes through to work on that later.
* The code should work if a player changes weapons. The amount of damage applied gets fetched from the player's active gun so changing the gun would theoretically change the amount of damage as well.

**Comment by lyonelz96** [comment]
@yshrdbrn 

 - Cool, so took a look at a different weapon (Sniper) and the damage seemed way too low. But took a look at the Weapons script and the Damage is the same as the AR. In the end your code is fine, we just have to adjust the damage later.

Looks good!

**Comment by yshrdbrn** [comment]
@lyonelz96 yeah we need to balance the damages. I remember changing the AR damage so it was easier to kill the enemy but I didn't change the other guns' damages. Anyway, thanks dude! 😄

**Pull request merged**
