### PR TITLE
Drop flag

### PR DESCRIPTION
**Pull request by stevau5**
## What issue is this PR solving?
Closes: https://github.com/Luna-Interactive/catastrophe/issues/73, https://github.com/Luna-Interactive/catastrophe/issues/64

## Description of change
What is being added or modified with this pull request?
Players can now Pickup and Drop the flag as many times as they like. This mechanic will be used for cycling the flag in order to shoot back at enemies. 

## How to reproduce the changes
Please describe step by step how to reproduce your changes.
Start Game, Grab Flag, Drop Flag. 

## Screenshots or GIFs
ezgif com-video-to-gif

### CODE REVIEW

**Comment by yshrdbrn** [comment]
Btw I suggest squashing all commits into one for this PR

**Comment by stevau5** [comment]
@mjimenez98 @yshrdbrn Okay so there is a specific reason I made it escape for the time being.. There is an issue with holding e for dropping and holding e for picking up.

The player can't precisely take their finger off e at the exact time, so the next animation executes when you don't really want it to. i suggest one we make it another button, not escape. But maybe Q or F.

**Comment by mjimenez98** [comment]
@stevau5 Were you able to try setting a timer? Like a "cooldown" mechanic as @gnoriega27 suggested. How does that sound?

**Comment by yshrdbrn** [comment]
I much changing the flag-taking mechanic from holding E to just pressing E. That way the issue Steven mentioned doesn’t happen and flag interactions are consistent

**Comment by mjimenez98** [comment]
@yshrdbrn Would you be able to cancel the taking action in the middle of it?

**Comment by yshrdbrn** [comment]
Yes, moving the player or reloading cancels the action.

**Comment by stevau5** [comment]
@yshrdbrn I like this approach

**Comment by mjimenez98** [comment]
Sounds great then! Let's do this 🙌

**Comment by gnoriega27** [comment]
I believe this approach would close #64

**Comment by yshrdbrn** [comment]
@mjimenez98 @stevau5 I changed the behavior so now taking and drop the flag is done by pressing `E`. You can cancel the flag-taking process by moving (not reloading).

Let me know what you think! Thanks!  😀

**Comment by stevau5** [comment]
Working!

**Pull request merged**
